version: '3.7'

services:
  #name this server
  jupyter_server:
    image: centos:test
    
    ports:
      - '8888:8888'
    volumes:
      - 'D:\Bankup-File\docker\python:/usr/src'

  db:
    image: mysql:test

    ports:
      - '3306:3306'

    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
    
    volumes:
      - 'D:\Bankup-File\docker\python:/usr/src'

    